// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZGydwwJMWlfl2eg1HFNYPV0P56xTNcg',
    appId: '1:950107640799:web:ecb07e4ba6f808a99bea6a',
    messagingSenderId: '950107640799',
    projectId: 'cues-1ced9',
    authDomain: 'cues-1ced9.firebaseapp.com',
    storageBucket: 'cues-1ced9.firebasestorage.app',
    measurementId: 'G-7P4BYJEJ2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrnpjX9SYMZzJo7VsqnTT6kq5eFjY3Eo',
    appId: '1:950107640799:android:01e946dd1b562db79bea6a',
    messagingSenderId: '950107640799',
    projectId: 'cues-1ced9',
    storageBucket: 'cues-1ced9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGi4uwxIuHk_zts0CgeZjyZyLnUoRSrao',
    appId: '1:950107640799:ios:50c936e4ab4cc6f99bea6a',
    messagingSenderId: '950107640799',
    projectId: 'cues-1ced9',
    storageBucket: 'cues-1ced9.firebasestorage.app',
    iosBundleId: 'com.example.cue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGi4uwxIuHk_zts0CgeZjyZyLnUoRSrao',
    appId: '1:950107640799:ios:50c936e4ab4cc6f99bea6a',
    messagingSenderId: '950107640799',
    projectId: 'cues-1ced9',
    storageBucket: 'cues-1ced9.firebasestorage.app',
    iosBundleId: 'com.example.cue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpZGydwwJMWlfl2eg1HFNYPV0P56xTNcg',
    appId: '1:950107640799:web:09c8d7c813ba6e589bea6a',
    messagingSenderId: '950107640799',
    projectId: 'cues-1ced9',
    authDomain: 'cues-1ced9.firebaseapp.com',
    storageBucket: 'cues-1ced9.firebasestorage.app',
    measurementId: 'G-QY1M98EP2Q',
  );
}
