// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ681Ji9GaJetudrw-mKAuHkoPBwtPa0k',
    appId: '1:300393022724:web:891f98d87bc1f4f538bc51',
    messagingSenderId: '300393022724',
    projectId: 'cue-hq',
    authDomain: 'cue-hq.firebaseapp.com',
    storageBucket: 'cue-hq.firebasestorage.app',
    measurementId: 'G-64XFKG1912',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiCcMGr8MW-BIT4zcBjEpnlTlaTT2FiBQ',
    appId: '1:300393022724:android:9f12ca1927255be938bc51',
    messagingSenderId: '300393022724',
    projectId: 'cue-hq',
    storageBucket: 'cue-hq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdX-1ERoK67K_I_Gra-A-mhUJ7wvjUkok',
    appId: '1:300393022724:ios:5255de72cfe8739b38bc51',
    messagingSenderId: '300393022724',
    projectId: 'cue-hq',
    storageBucket: 'cue-hq.firebasestorage.app',
    iosBundleId: 'com.cuehq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdX-1ERoK67K_I_Gra-A-mhUJ7wvjUkok',
    appId: '1:300393022724:ios:99ee30b8c8f73c9c38bc51',
    messagingSenderId: '300393022724',
    projectId: 'cue-hq',
    storageBucket: 'cue-hq.firebasestorage.app',
    iosBundleId: 'com.example.cue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ681Ji9GaJetudrw-mKAuHkoPBwtPa0k',
    appId: '1:300393022724:web:17c0cdc76be679c838bc51',
    messagingSenderId: '300393022724',
    projectId: 'cue-hq',
    authDomain: 'cue-hq.firebaseapp.com',
    storageBucket: 'cue-hq.firebasestorage.app',
    measurementId: 'G-RPXMBV25V7',
  );

}